max_requests: 100
max_workers: 10
runner_name: "python-sandbox"
proxy:
#  http: "http://127.0.0.1:2334"
#  https: "http://127.0.0.1:2334"
#  socks5: "socks5://127.0.0.1:2333"

# sandbox
python_path: "/usr/local/bin/python3"
python_lib_path: ""
# nodejs_path: "/usr/local/bin/node"

# allowed_syscalls: []
